### DISCUSSION TITLE
Koordinator支持YARN生态与K8s混部

### DISCUSSION THREAD

**Discussion by zwzhang0107** [koordinator-sh/koordinator#1297] [Ideas]
# 背景

## Haddop YARN架构
- 传统的Master-Slave架构，RM在中心侧，NM在单机侧
- RM与NM之间以心跳方式沟通，NM上报节点资源信息，RM负责资源调度。
- 提供对应用资源管理的抽象协议Application，应用提交时首先向RM申请资源，申请到资源后向NM启动任务进程。
- YARN要求应用遵循ApplicationMaster和ApplicationSlave的设计，作业提交后首先启动AM，AM负责AS的资源申请和启动。
![image](https://github.com/koordinator-sh/koordinator/assets/101699117/2da7d5b7-df50-4c87-95f1-8ac7da92428c)

## Koordiantor混部超卖模型
- 将资源分为Product、Batch多个优先级
- Product总量对应的是物理资源（allocatable），Batch是超卖资源，总量是根据节点的实际利用率，动态计算得到
- 超卖的Batch资源量以extend resource的形式更新在Node上
![image](https://github.com/koordinator-sh/koordinator/assets/101699117/41e421f5-ac46-4095-92e9-6b2974e0b2ab)

```yaml
#Node
status:
  allocatable:
    # 单位为千分之一核，以下表示50核。
    kubernetes.io/batch-cpu: 50000
    # 单位为字节，以下表示50 GB。
    kubernetes.io/batch-memory: 53687091200
```

## 混部场景
- YARN生态支持了大量任务类型的应用场景
- 虽然部分大数据应用已经做了K8s operator化改造，但由于功能丰富度、历史遗留等原因，无法顺利的将应用切为K8s
- YARN生态与K8s生态缺少配合，资源无法打通共享，更无法实现混部超卖

# 总体原则

1. Koordinator社区基于Hadoop-YARN开源版本，原则上不对K8s原生和YARN组件做侵入式改造
2. 同一节点的Batch资源即可被K8s Pod使用，也可被YARN task使用
3. YARN Task的单机资源使用，需要被Koordinator的QoS策略管理

# 关键设计
## 资源超卖与分配
![updateResource](https://github.com/koordinator-sh/koordinator/assets/101699117/bb4ff1ea-eef7-48e4-aa92-3293eeeda940)

1. koordlet上报资源用量信息，slo-controller计算节点Batch资源账本，以extended-resource形式更新到Node
2. kilo-controller同步node的Batch资源总量和Pod已申请量，将未分配的资源量（Total-Requested）同步至YARN RM（RPC调用）
3. kilo-controller从YARN-RM同步已分配资源量，更新到Node的Annotation中
```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    koordinator.sh/resourceAllocated: '{"yarnAllocated":{"kubernetes.io/batch-cpu": "10k", "kubernetes.io/batch-memory": "15Gi"}}'
    ...
status:
  allocatable:
    kubernetes.io/batch-cpu: 30k
    kubernetes.io/batch-memory: 20Gi
```
## 节点运行时管理
![node-runtime](https://github.com/koordinator-sh/koordinator/assets/101699117/1d19848b-6f75-4b72-aa67-2ae71796a1f3)

1. YARN的Task以LinuxContainerExecutor模式运行，每个Task对应一个单独的cgroup目录
2. YARN-NM以Pod形式部署在节点，Task由Nodemanager拉起并分配Cgorup目录
3. 为了区分YARN-NM自身和YARN Task的资源管理，宿主机的cgroup目录会被挂载到YARN Pod内，由NM指定参数配置
![node-runtime-cgroup drawio](https://github.com/koordinator-sh/koordinator/assets/101699117/e5e37a0e-6fc9-4bb5-8c29-209b9fb4b754)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: yarn-node-manager
spec:
  containers:
    name: node-manager
    command:
    - start-node-manager.sh
    # ......
    volumeMounts:
    - mountPath: /host-cgroup/
      name: host-cgroup-root
- hostPath:
      path: /sys/fs/cgroup/ # cgroupfs和systemd路径格式不同，这里直接挂载根组，启动脚本根据环境设置nm配置
      type: ""
    name: host-cgroup-root
```
```xml
<configuration>
  <property>
    <name>yarn.nodemanager.linux-container-executor.cgroups.mount-path</name>
    <value>/host-cgroup/</value>
  </property>
  <property>
    <name>yarn.nodemanager.linux-container-executor.cgroups.hierarchy</name>
    <value>/kubepods.slice/kubepods-besteffort.slice/hadoop-yarn</value>
  </property>
</configuration>
```

<details>
<summary>其他cgroup管理机制</summary>

![node-runtime-cgroup-backup drawio](https://github.com/koordinator-sh/koordinator/assets/101699117/12ba60c5-4dbc-4258-b3f8-59590e4fc716)
</details>

## 单机QoS保障策略
- 静态策略需要考虑hadoop-yarn的cgroup目录（CPU Group Identity，Memory QoS，LLC及MBA隔离）
- 动态策略需要koord-yarn-copilot提供用量信息和task元信息
   - 驱逐策略需要考虑YARN任务的频繁起停，导致kill的task已经不存在的情况
- YARN Task驱逐需要考虑优雅退出方案（kill -15），避免YARN Application直接失败

![koord-yarn-copilot drawio](https://github.com/koordinator-sh/koordinator/assets/101699117/8cb9b712-513c-4cf1-875b-787e2c292024)

1. koord-yarn-copilot作为单机侧koordlet和YARN-NM之间的沟通桥梁，以sidercar容器的形式同koordlet部署在一起
2. koordlet的states informer模块从koord-yarn-copilot获取task元信息
3. koordlet的metrics advisor模块从koord-yarn-copilot中获取资源用量信息，koord-yarn-copilot直接提供Prometheus格式的API接口，可以同时满足可观测性指标链路的需求
4. koordlet中metric cache支持来自第三方指标的数据存储，可以自定义保存时间
5. koordlet的qos manager策略兼容YARN task的目录，对于驱逐操作需要调用koord-yarn-copilot的RPC接口

| QoS策略 | 当前实现方式 | YARN适配方案 |
| --- | --- | --- |
| CPU Group Identity | guarantee pod及burstable分组整体设2；离线besteffort分组整体设-1 | hadoop-yarn在besteffort下，天然适配 |
| CPU Suppress | 根据节点负载和在线Pod的负载，在container级别修改离线Pod的CPU绑核 | 修改hadoop-yarn目录整体的cpuset |
| Memory QoS for 离线 | 离线Pod设置memoryWmarkMinAdj（优先回收page cache），memoryOomKillGroup（cgroup级别OOM时整组kill） | 设置hadoop-yarn目录的memoryWmarkMinAdj及memoryOomKillGroup |
| Memory Evict | 根据节点用量水位，选择低优先级的离线Pod进行kill | koordlet从koord-yarn-copilot获取usage和task信息，综合优先级选择要kill的task，将要kill的task发送给koord-yarn-copilot。<br>由于离线频繁起停，koord-yarn-copilot需要考虑要kill的task已经不存在的情况。例如koordlet将需要回收的内存量和sorted task list发送给koord-yarn-copilot。<br>考虑给haoop-yarn整组设置memory.limit，控制oom范围降低稳定性风险。 |
| CPU Evict | 读取besteffort cgorup分组中的cpu用量和限制信息(cpuset压制看container级别，cfs quota压制看根组），计算资源满足度，根据优先级选择pod进行kill。 | 读取限制信息时考虑hadoop-yarn目录，和koord-yarn-copilot配合驱逐task（与Memory Evict）类似。 |
| LLC及MBA隔离 | 读取CPU container cgroup级别的tasks id，将其放入到对应的resctrl分组中 | 方案一：将hadoop-yarn的cgroup子目录中的task id放入到对应的resctrl分组（离线频繁起停可能来不及）<br>方案二：直接将node manager的进程id设置到resctrl-BE分组，需要确定container级别是否会自动继承 |
| BlkIO QoS | Doing | TBD |

#### 组件管理

- YARN-NM从RM摘除时，需要修改YARN RM在节点上的配置文件，然后调用RPC接口refreshNode
- 因此考虑将YARN-RM以Pod形式托管，定义在YARN Spec CRD中，相关配置文件通过configmap形式挂载到Pod内部的路径中
- YARN Operator 根据YARN Spec CRD扩缩YARN NM Pod
- 摘除NM节点时，YARN Operator首先更新ConfigMap内容，然后RPC调用refreshNode，考虑到ConfigMap的同步，需要保证最终一致性

![yarn-autoscaler](https://github.com/koordinator-sh/koordinator/assets/101699117/4e9711ea-78bb-4e1a-ad21-7ebf09d63041)

<details>
<summary>其他方案</summary>
其他方案
YARN-RM继续保留在ECS模式下托管，RM同节点需要部署Koordiantor工具套装，负责节点摘除等需要修改本地配置的操作。

![yarn-operator-backup drawio](https://github.com/koordinator-sh/koordinator/assets/101699117/794366c9-7f42-40c3-9533-8adafd3b82fe)

两者相比，RM用Pod方式托管的优点在于统一维护，方便管理，YARN组件由K8s生态全托管，缺点在于对现有的运维链路改造会更大；而RM用ECS托管的优点在于对现有运维链路的改动较小，但缺点在于运维操作分散，维护复杂度高，操作和配置流程会有一部分转移到YARN Spec中，另一部分保留在原流程不变，管理上容易出现冲突。

</details>

#### 日常运维
通常包括以下场景：

- YARN集群配置修改
- 节点扩缩容
- 队列创建，Quota容量修改

与业务相关的运维操作管理保持不变，运维组件和YARN RM/NM在同一个容器内部署，操作YARN RM/NM。
与节点扩缩容相关的参考组件管理流程，通过Koordinator定义的CRD扩容

#### 演进方案
阶段1：Koordinator只托管Node Manager，不含运维控制链路

1. 搭建K8s集群，部署Koordinator
2. 搭建YARN集群，以ECS的形式部署RM
3. 以Pod的形式部署NM，使用Koordinator YARN Operator的CRD托管
4. NM的配置，扩缩均通过Koordinator YARN Operator

阶段2：YARN-RM的托管部署纳入到Koordiantor，支持运维链路对接

1. 搭建K8s集群，部署Koordinator
2. 以Pod的形式部署RM和NM，使用Koordinator YARN Operator的CRD托管
3. RM/NM的Pod中包含相关的运维组件进程
4. 集群节点扩缩相关的操作对接Koordinator YARN Operator
5. 日常的操作由运维组件支持

阶段0：最小可用版本，不支持YARN组件自动部署和运维操作

1. 手动将NM以Pod形式部署
2. RM继续沿用当前的集群形态，以进程形式在 ECS 部署，离线没有混部资源可用时，将节点资源置为零

![yarn-autoscale-backup drawio](https://github.com/koordinator-sh/koordinator/assets/101699117/a7701109-d75c-43f2-ad64-d1724842f89b)

# 阶段性目标
## milestone 1.0 (6.10功能研发完成)

- K8s集群的Batch资源可以共享给YARN使用
- YARN的Task在运行时可以受到单机QoS策略的管理约束
### 功能拆解

- kilo-controller支持将可用的batch资源同步到YARN-RM
- YARN-NM支持以Pod形式部署运行
- 单机QoS策略适配YARN Task（CPU压制、BVT、内存水位驱逐）
## milestone 1.1 (精细化策略-8月中)

- K8s的Batch资源调度需要感知YARN的分配情况
- 单机QoS策略精细化管理，支持按公平性等策略驱逐或压制YARN Task
- 其他单机QoS策略适配YARN Task
## milestone 1.2 (NM管理)

- YARN NM的生命周期管理由kilo-controller托管
- 支持YARN NM优雅完备的上下线流程，如资源不足时直接将nm下线
- YARN Task优雅驱逐
## milestone 2.0

- 具备YARN RM完整的托管能力
- 提供YARN集群的运维管理能力
- YARN资源容量画像，结合队列Quota管理
- 单机QoS能力优化

TBD
# 待讨论议题

1. 组件命名
   a. kilo，取自航海过程中使用的旗语单词，两艘船碰面时打出kilo，表示“I wish to communicate with you.”，意在希望K8s和YARN生态能够在混部场景可以及时互通，稳定运行。
   b. conductor，指挥家
2. 项目工程建设
  a. pkg/kilo-controller，用于koordiantor和yarn之间资源同步的controller
  b. pkg/yarn-operator，用于yarn组件管理
  c. pkg/koord-copilot-yarn，负责单机侧与YARN-NM交互，Task信息管理/驱逐
