### ISSUE TITLE
[BUG] Colocation profile conflicts with LimitRange policy

### ISSUE THREAD

**Issue by jiasheng55** [koordinator-sh/koordinator#1344]
**What happened**:
1. LimitRange was applied to set default cpu/memory:
```
spec:
  limits:
  - max:
      cpu: "16"
      memory: 30Gi
    type: Pod
  - default:
      cpu: "2"
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 500Mi
    max:
      cpu: "16"
      memory: 16Gi
    type: Container
```

2. Colocation Profile was installed to convert `cpu/memory` resources to `batch-cpu/memory` resources.

3. Apply a deployment with below config:
```
...
        resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
...
```

4. Pods failed to create with error:
```
message: 'failed to start container "c309080380e3ad68168c38ed41d31ef88ec07f8e82129abe4fea22c34f5984d6":
          Error response from daemon: OCI runtime create failed: container_linux.go:345:
          starting container process caused "process_linux.go:424: container init
          caused \"process_linux.go:390: setting cgroup config for procHooks process
          caused \\\"failed to write 200000 to cpu.cfs_quota_us: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podb78b176d-a2c9-450b-8685-7bca839ba191/c309080380e3ad68168c38ed41d31ef88ec07f8e82129abe4fea22c34f5984d6/cpu.cfs_quota_us:
          invalid argument\\\"\"": unknown'
```

5. Check the Pod spec, it turns out both `cpu/memory` and `batch-cpu/memory` were set, which caused conflicts.
```
resources:
      limits:
        cpu: "2"
        kubernetes.io/batch-cpu: "1"
        kubernetes.io/batch-memory: 1Gi
        memory: 2Gi
      requests:
        cpu: 100m
        kubernetes.io/batch-cpu: "1"
        kubernetes.io/batch-memory: 1Gi
        memory: 500Mi
```

**What you expected to happen**:

"Colocation Profile" and "LimitRange with default cpu/memory configuration" could co-exist.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`): **1.21** and **1.17**
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:
