### ISSUE TITLE
[proposal] koordlet identifies and reports the NUMA stats

### ISSUE THREAD

**Issue by saintube** [koordinator-sh/koordinator#1503]
**What is your proposal**:

The koordlet should support identifying, collecting, and reporting the NUMA stats. e.g. The memory total of the numa node 0.

**Why is this needed**:

Currently, the koordlet reports the node memory usage without NUMA awareness while it does have part of NUMA information like CPU topology. For some QoS strategies like BECPUSuppress, it checks the cpu topology to pick a good binding result. However, for some platforms like ARM the NUMA locality can be essential for the app performance. The koordlet is expected to identify the NUMA stats and report them so that the NUMA locality problem can be better handled in the scheduling and QoS management. e.g. To balance the memory util between numa nodes when an LSR pod is scheduled.

Related Issues/PRs: #228, #1224.

**Is there a suggested solution, if so, please add it**:

See #1516.

- Add collection for the cpu/memory capacity collection per NUMA.
     - [x] util/system: Add collection logic for NUMA stats. Related system interfaces: `/sys/devices/system/node/nodeX/meminfo`.
     - [x] metrics advisor & metric cache: Store the NUMA info into the storage with the key `NodeMemoryInfo`.
- Add the numa stats reporting in the NRT states informer.
     - [x] states informer: In the nodetopo informer, fetch the NUMA info and kubelet topology policy, report them onto NRT.

NRT example:

```yaml
apiVersion: topology.node.k8s.io/v1alpha1
kind: NodeResourceTopology
metadata:
  name: test-node
  annotations:
    node.koordinator.sh/cpu-shared-pools: "{...}"
    node.koordinator.sh/cpu-topology: "{...}"
    # ...
# change fields: `topologyPolicies`, `zones`
topologyPolicies: ["RestrictedContainerLevel"]
zones:
  - name: numa-node-0
    type: Node
    resources:
      - name: cpu
        capacity: 26
        allocatable: 26
      - name: memory
        capacity: 184Gi
        allocatable: 180Gi
  - name: numa-node-1
    type: Node
    resources:
      - name: cpu
        capacity: 4
        allocatable: 3
      - name: memory
        capacity: 184Gi
        allocatable: 180Gi
```
