### ISSUE TITLE
[BUG] ClusterColocationProfile conflicts with ResourceQuota

### ISSUE THREAD

**Issue by jiasheng55** [koordinator-sh/koordinator#1676]
**What happened**:
1. Namespace has ResourceQuota config:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test
  namespace: test
spec:
  hard:
    limits.cpu: "10"
    limits.memory: 10Gi
    requests.cpu: "10"
    requests.memory: 10Gi
```
2. Koordinator has ClusterColocationProfile like [what the documents described](https://koordinator.sh/zh-Hans/docs/user-manuals/colocation-profile#%E5%88%9B%E5%BB%BA-clustercolocationprofile).
3. When submitting new Pods, it failed with error messages:
```
message: 'admission webhook "xxx" denied the request: pods "xxx" is forbidden: failed quota: test: **must specify limits.cpu,limits.memory,requests.cpu,requests.memory**'
```

**What you expected to happen**:
ClusterColocationProfile can co-exist with ResourceQuota

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: v1.2
- Kubernetes version (use `kubectl version`): v1.21.3
