### ISSUE TITLE
[proposal] QoS supports of Hadoop YARN task in koordlet/slo-controller

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#1727]
**What is your proposal**:
Koordinator is almost ready to support running Hadoop YARN tasks as Batch+BE QoS in K8s. Here are the [detailed design](https://github.com/koordinator-sh/koordinator/discussions/1297).

Since YARN tasks are running under a specified cgroup path(kubepods/besteffort/hadoop-yarn), koordinator should take the tasks into account during Batch resource calculation and QoS Management.

**Why is this needed**:
Resource usage of YARN tasks will be count as system usage if koordlet dose not collect it independently, which leads to the miscalculation of `Batch Allocatable` and the omission of QoS Management.

**Is there a suggested solution, if so, please add it**:
Define YARN tasks as out-of-band Host Application, see the [api design](https://github.com/koordinator-sh/koordinator/pull/1508/files#diff-00b2f1de4aa8c404e9eb52c7390c2bb47f04454be559c57577d61a4bb19b3cdd) for more details.
```yaml
  host-application-config: |
    {
      "applications": [
        {
          "name": "yarn-task",
          "priority": "koord-batch",
          "qos": "BE",
          "cgroupPath": {
            "base": "CgroupBaseTypeKubeBesteffort",
            "parentDir": "./",
            "relativePath": "hadoop-yarn/",
          }
        }
      ]
    }
```
- [x] add plugin in koordlet metricAdvisor for collecting the resource usage of host-applications by cgroup path.(@zwzhang0107)
- [x] koordlet statesInformer reports the hosts application resource usage  in [NodeMetric](https://github.com/koordinator-sh/koordinator/pull/1725). 
- [x] slo-controller treats resource usage of YARN tasks as batch prioirty during caculcating batch allocatable
- [x] slo-controller exclude yarrn allocated from node annotation when calculating k8s batch allocatable
- [x] CPUSuppress strategy should exclude YARN tasks during [system usage calculation](https://github.com/koordinator-sh/koordinator/blob/main/pkg/koordlet/qosmanager/plugins/cpusuppress/cpu_suppress.go#L166).
- [ ] add plugin in statesInformer for collecting YARN task info from yarn-copilot, which will be used for startegies like memory eviction.
- [ ] MemoryEvict strategy should consider YARN tasks during [eviction](https://github.com/koordinator-sh/koordinator/blob/main/pkg/koordlet/qosmanager/plugins/memoryevict/memory_evict.go#L164). since the strategy may kill batch pods/YARN tasks at the same time. koordlet should consider the request/usage of hadoop tasks for fairness.

support static qos stragegy for host application(#1639)
- [ ] LLC/MBA insolation should consider YARN tasks pids.
- [x] group identity plugin consider YARN cgroup dir.
- [ ] set memory qos for YARN cgroup dir.
