### ISSUE TITLE
[BUG]Resource types cannot be added to elasticquota, and the webhook check item checkSubAndParentGroupMaxQuotaKeySame fails.

### ISSUE THREAD

**Issue by qinfustu** [koordinator-sh/koordinator#1747]
**What happened**:
Resource types cannot be added to elasticquota, and the webhook check item checkSubAndParentGroupMaxQuotaKeySame fails.
e.g. 
parent quotal
```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-parent
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/parent: ""
    quota.scheduling.koordinator.sh/is-parent: "false"
spec:
  max:
    cpu: 40
    memory: 40Gi
  min:
    cpu: 10
    memory: 20Mi
```
sub quota
```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-sub
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/parent: "quota-parent"
    quota.scheduling.koordinator.sh/is-parent: "false"
spec:
  max:
    cpu: 40
    memory: 40Gi
  min:
    cpu: 10
    memory: 20Mi
```
When the resource type [kubernetes.io/gpu-core] is added to the parent or sub quota, an error is reported. The error is as follows:
```sh
Error from server: error when replacing "xxx": admission webhook "velasticquota.kb.io" denied the request: checkSubAndParentGroupMaxQuotaKeySame failed: quota-parent's key is not the same with quota-sub
```
Expect sub quota
```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-sub
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/parent: "quota-parent"
    quota.scheduling.koordinator.sh/is-parent: "false"
spec:
  max:
    cpu: 40
    memory: 40Gi
    kubernetes.io/gpu-core: "100"
  min:
    cpu: 10
    memory: 20Mi
    kubernetes.io/gpu-core: "100"
```
**What you expected to happen**:
Add a new resource type without deleting quota

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: 1.20
- Kubernetes version (use `kubectl version`): 1.19
- Install details (e.g. helm install args): 
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:
