### ISSUE TITLE
[question]差异化SLO混部场景下，在线服务RT性能比在线服务单独部署还好

### ISSUE THREAD

**Issue by openxxs** [koordinator-sh/koordinator#1816]
**What happened:**
根据 [阿里云在线服务与视频转码应用混部](https://www.alibabacloud.com/help/zh/ack/ack-managed-and-ack-dedicated/user-guide/deploy-an-online-service-and-a-video-transcoding-application-on-the-same-node?spm=a2c63.p38356.0.0.5d2d1702c1pXvx#p-af0-zen-ggx) 最佳实践进行压测，压测结果不符合预期：对照组和实验组的Nginx RT性能均优于基线。可以稳定复现。

**What you expected to happen:**
如最佳实践预期结果所示，对照组（k8s默认混合部署）和实验组（差异化SLO混部）的RT性能均应低于基线（在线应用独立部署）。
目前猜测为混部场景下，请求Nginx的Request数量少了，因此体现出的RT90和RT99较好，但无法证实。

**Environment:**

- Koordinator version: - v1.3.0
- Kubernetes version (use kubectl version): v1.24.4
- docker/containerd version: containerd://1.7.11
- OS (e.g: cat /etc/os-release): BaiduLinux 3
- Kernel (e.g. uname -a): Linux cce-afp8e2up-99bb2eo9 5.10.0-3.0.1.5 # 14 SMP Wed Mar 29 10:56:13 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
- 内核版本：5.10.134-15.2.an8.x86_64
- 系统架构：AMD64

**Anything else we need to know:**

***实验过程***

分别在nginx（基线）和nginx + ffmpeg（实验组）两个场景下，进行加压操作：`./wrk -t6 -c54 -d60s --latency http://172.24.xx.xx:8000/`

单独nginx测试结果：
```
  6 threads and 54 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.00ms    3.02ms  38.15ms   95.78%
    Req/Sec    27.37k     1.93k   36.60k    71.78%
  Latency Distribution
     50%  200.00us
     75%  484.00us
     90%    1.55ms
     99%   18.80ms
  9817294 requests in 1.00m, 7.77GB read
Requests/sec: 163366.41
Transfer/sec: 132.42MB
```
nginx + ffmpeg 混部测试结果：
```
  6 threads and 54 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.86ms    3.43ms 119.71ms   96.94%
    Req/Sec    26.76k     2.27k   36.72k    76.17%
  Latency Distribution
     50%  217.00us
     75%  490.00us
     90%    1.50ms
     99%   14.04ms
  9592626 requests in 1.00m, 7.59GB read
Requests/sec: 159631.20
Transfer/sec: 129.39MB
```

Nginx Yaml：

```yaml
---
# nginx应用配置
apiVersion: v1
data:
  config: |-
    user  nginx;
    worker_processes  80; # Nginx的Worker个数，影响Nginx Server的并发。

    events {
        worker_connections  1024;  # 默认值为1024。
    }

    http {
        server {
            listen  8000;

            gzip off;
            gzip_min_length 32;
            gzip_http_version 1.0;
            gzip_comp_level 3;
            gzip_types *;
        }
    }

    #daemon off;
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: liks-system
---
# Nginx实例，作为在线类型服务应用。
apiVersion: v1
kind: Pod
metadata:
  labels:
    koordinator.sh/qosClass: LS
    app: nginx
  name: nginx
  namespace: liks-system
spec:
  containers:
    - image: 'koordinatorsh/nginx:v1.18-koord-exmaple'
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 8000
          hostPort: 8000 # 压测请求访问的端口。
          protocol: TCP
      resources:
        limits:
          cpu: '16'
          memory: 10Gi
        requests:
          cpu: '16'
          memory: 10Gi
      volumeMounts:
        - mountPath: /apps/nginx/conf
          name: config
  hostNetwork: true
  restartPolicy: Never
  volumes:
    - configMap:
        items:
          - key: config
            path: nginx.conf
        name: nginx-conf
      name: config
  nodeName: 172.24.xx.xx  # 请替换为您的测试机的节点名称。
```

be-ffmpeg.yaml：

```yaml
# FFmpeg实例，作为离线类型计算应用。
apiVersion: v1
kind: Pod
metadata:
  name: be-ffmpeg
  namespace: liks-system
  labels:
    app: be-ffmpeg
  # 1. 按照K8s默认混合部署模式部署：删除以下koordinator.sh/qosClass=BE的label。
  # 2. 按照ACK差异化SLO混部模式部署：保留以下koordinator.sh/qosClass=BE的label。
    koordinator.sh/qosClass: BE
spec:
  priorityClassName: koord-batch
  containers:
    # FFmpeg的进程数量可以根据测试需求调节，进程数越多对应的离线资源使用率越高，默认为25个进程，每个进程有两个线程并发工作。
    - command:
        - start-ffmpeg.sh
        - '25'
        - '2'
        - /apps/ffmpeg/input/HD2-h264.ts
        - /apps/ffmpeg/
      image: 'registry.cn-zhangjiakou.aliyuncs.com/acs/ffmpeg-4-4-1-for-slo-test:v0.1'
      imagePullPolicy: IfNotPresent
      name: ffmpeg
      resources:
      # 1. 按照K8s默认混合部署模式部署：删除以下扩展资源kubernetes.io/batch-cpu和kubernetes.io/batch-memory。
      # 2. 按照ACK差异化SLO混部模式部署：保留以下扩展资源kubernetes.io/batch-cpu和kubernetes.io/batch-memory。
      # 具体资源需求量请按节点规格按需调整。
        limits:
          kubernetes.io/batch-cpu: 10k
          kubernetes.io/batch-memory: 20Gi
        requests:
          kubernetes.io/batch-cpu: 10k
          kubernetes.io/batch-memory: 20Gi
  hostNetwork: true
  restartPolicy: Never
  nodeName: 172.24.xx.xx
```
