### ISSUE TITLE
[question] deploy failed to try resolving symlinks in path "/var/log/pods/koordinator-system_koord-manager-/manager/200.log": lstat : no such file or directory

### ISSUE THREAD

**Issue by kavita1205** [koordinator-sh/koordinator#2034]
**What happened**: 
We have installed koordinator using helm chart mentioned in the documentation [https://koordinator.sh/docs/installation/](https://github.com/koordinator-sh/koordinator/issues/url) and we are getting crashloopbackoff for koordlet. Can someone please help me here, how to fix this issue.

```
kubectl get po -n koordinator-system|grep -v Running
NAME                                 READY   STATUS             RESTARTS        AGE
koord-manager-889449d7b-4rm2c        0/1     CrashLoopBackOff   201 (62s ago)   4d
          <none>
```

When I checked the logs , I found below error:

```
 kubectl logs -n koordinator-system koord-manager-889449d7b-4rm2c
failed to try resolving symlinks in path "/var/log/pods/koordinator-system_koord-manager-889449d7b-4rm2c_deb57dfe-769a-440c-9bce-c0af1f0dda2f/manager/200.log": lstat /var/log/pods/koordinator-system_koord-manager-889449d7b-4rm2c_deb57dfe-769a-440c-9bce-c0af1f0dda2f/manager/200.log: no such file or directory
```
below is the values.yaml

```
# Default values for koordinator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

crds:
  managed: true

# values for koordinator installation
installation:
  namespace: koordinator-system
  roleListGroups:
    - '*'

featureGates: ""

imageRepositoryHost: ghcr.io

koordlet:
  image:
    repository: koordinator-sh/koordlet
    tag: "v1.4.1"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 256Mi
  features: ""
  log:
    # log level for koordlet
    level: "4"
  hostDirs:
    kubeletConfigDir: /etc/kubernetes/
    kubeletLibDir: /var/lib/kubelet/
    koordProxyRegisterDir: /etc/runtime/hookserver.d/
    koordletSockDir: /var/run/koordlet
    predictionCheckpointDir: /var/run/koordlet/prediction-checkpoints
    # if not specified, use tmpfs by default
    koordletTSDBDir: ""
  enableServiceMonitor: false


manager:
  # settings for log print
  log:
    # log level for koord-manager
    level: "4"

  replicas: 5
  image:
    repository: koordinator-sh/koord-manager
    tag: "v1.4.1"
  webhook:
    port: 9876
  metrics:
    port: 8080
  healthProbe:
    port: 8000

  resyncPeriod: "0"

  # resources of koord-manager container
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 256Mi

  hostNetwork: false

  nodeAffinity: {}
  nodeSelector: 
    node-role.kubernetes.io/control-plane: ""
  tolerations: 
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"

webhookConfiguration:
  failurePolicy:
    pods: Ignore
    elasticquotas: Ignore
    nodeStatus: Ignore
    nodes: Ignore
  timeoutSeconds: 30

serviceAccount:
  annotations: {}


scheduler:
  # settings for log print
  log:
    # log level for koord-scheduler
    level: "4"

  replicas: 5
  image:
    repository: koordinator-sh/koord-scheduler
    tag: "v1.4.1"
  port: 10251

  # feature-gates for k8s > 1.22
  featureGates: ""
  # feature-gates for k8s 1.22
  compatible122FeatureGates: "CompatibleCSIStorageCapacity=true"
  # feature-gates for k8s < 1.22
  compatibleBelow122FeatureGates: "DisableCSIStorageCapacityInformer=true,CompatiblePodDisruptionBudget=true"

  # resources of koord-scheduler container
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 256Mi

  hostNetwork: false

  nodeAffinity: {}
  nodeSelector: 
    node-role.kubernetes.io/control-plane: ""
  tolerations: 
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"

descheduler:
  # settings for log print
  log:
    # log level for koord-descheduler
    level: "4"

  replicas: 2
  image:
    repository: koordinator-sh/koord-descheduler
    tag: "v1.4.1"
  port: 10251

  featureGates: ""

  # resources of koord-descheduler container
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 256Mi

  hostNetwork: false

  nodeAffinity: {}
  nodeSelector: 
    node-role.kubernetes.io/control-plane: ""
  tolerations: 
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"

```
**What you expected to happen**:
All pods should run properly without error.
**How to reproduce it (as minimally and precisely as possible)**:
You can use the values.yaml mentioned above and reproduce this issue.
**Anything else we need to know?**:

**Environment**:
- App version: 1.4.1
- Kubernetes version (use `kubectl version`):1.24
- Install details (e.g. helm install args): helm install koordinator koordinator-sh/koordinator --version 1.4.1 -f values.yaml
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version: Ubuntu 22.04
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:
