### ISSUE TITLE
[BUG] koord-descheduler: objectLimiter.workload doesn't work

### ISSUE THREAD

**Issue by songtao98** [koordinator-sh/koordinator#2074]
**What happened**:
The objectLimiter of workload cannot really limit number of pods evicted in version >= 1.4.0

**What you expected to happen**:
Pods being evicted should be limited.

**How to reproduce it (as minimally and precisely as possible)**:
1. install koordinator 1.4.0 or 1.4.1
2. edit koord-descheduler-config:
```
    apiVersion: descheduler/v1alpha2
    kind: DeschedulerConfiguration
    ...
    profiles:
    - name: koord-descheduler
      plugins:
        deschedule:
          enabled:
            - name: PodLifeTime
        evict:
          enabled:
            - name: MigrationController
      pluginConfig:
      - name: MigrationController
        args:
          apiVersion: descheduler/v1alpha2
          kind: MigrationControllerArgs
          defaultJobMode: EvictDirectly
          maxMigratingPerWorkload: 5
          maxUnavailablePerWorkload: 5
          objectLimiters:
            workload:
              duration: 5m
              maxMigrating: 1
      - name: PodLifeTime
        args:
          maxPodLifeTimeSeconds: 300
          namespaces:
            include:
            - "default"
```
3. deploy stress deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-demo
  namespace: default
  labels:
    app: stress-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: stress-demo
  template:
    metadata:
      name: stress-demo
      labels:
        app: stress-demo
    spec:
      containers:
        - args:
            - '--vm'
            - '2'
            - '--vm-bytes'
            - '1600M'
            - '-c'
            - '2'
            - '--vm-hang'
            - '2'
          command:
            - stress
          image: polinux/stress
          imagePullPolicy: Always
          name: stress
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
      restartPolicy: Always
```
5. after 5 miniutes, PodLifeTime evict 5 replicas of stress deployment at the same time. But the objectLimiter should make sure it evict only 1 pod of stress.
![image](https://github.com/koordinator-sh/koordinator/assets/110808397/d8f5de24-6e75-42e5-aefc-2a3b752fe8dd)

**Anything else we need to know?**:
Back to version 1.3.0 it's working. Version 1.4.0 introduced arbitration mechanism that might casue this problem. 

**Environment**:
- App version: >= 1.4.0
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:
