### ISSUE TITLE
[BUG] Koordinator doesn't support multiple card sharing

### ISSUE THREAD

**Issue by ZiMengSheng** [koordinator-sh/koordinator#2097]
**What happened**:

A node has 8 GPU cards, each GPU card has 80 Gi GPU memory. I want to use four cards, each GPU card 40 Gi GPU Memory via `koordinator.sh/gpu.shared`. But pod will stuck in Pending phase.
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  namespace: default
spec:
  schedulerName: koord-scheduler
  containers:
  - command:
    - sleep
    - 365d
    image: busybox
    imagePullPolicy: IfNotPresent
    name: curlimage
    resources:
      limits:
        cpu: 40m
        memory: 40Mi
        koordinator.sh/gpu.shared: "4"
        koordinator.sh/gpu-memory: 160Gi
      requests:
        cpu: 40m
        memory: 40Mi
        koordinator.sh/gpu.shared: "4"
        koordinator.sh/gpu-memory: 160Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  restartPolicy: Always
```

**What you expected to happen**:

Pod should be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:
