### ISSUE TITLE
[BUG] Elasticquota failed to update due to velasticquota verification

### ISSUE THREAD

**Issue by qinfustu** [koordinator-sh/koordinator#2220]
**What happened**:
The update of elasticquota failed, and the error reported was denied the request: checkMinQuotaSum all children's MinQuota > current MinQuota. However, in fact all children's MinQuota < current MinQuota. The following is the debug information

error: elasticquotas.scheduling.sigs.k8s.io "cluster-root-quota" could not be patched: admission webhook "velasticquota.koordinator.sh" denied the request: checkMinQuotaSum all children's MinQuota > current MinQuota, current: cluster-root-quota, childMinSum: cpu: 23838, **memory: 87751Gi**, gpu: 724, newQuotaInfoMin: cpu: 500k, **memory: 100000Gi**, gpu: 20k

Locate the problem lies in the LessThanOrEqualCompletely method. There is a problem with the value returned by the Value() method of corev1.ResourceList, which is inconsistent with String().

childMinSum: cpu: 23838, memory: 87751Gi, gpu: 724, newQuotaInfoMin: cpu: 500k, memory: 300000Gi, gpu: 20k
resource.go:274] delta: cpu: -476162, memory: -212249Gi, gpu: -19276
resource.go:276] k: **memory, value: 8894628506, valueS: -212249Gi**
resource.go:276] k: nvidia.com/gpu, value: -19276, valueS: -19276
resource.go:276] k: cpu, value: -476162, valueS: -476162

The current temporary processing strategy is to change value.Value() > 0 to value.Value() > 0 && !strings.Contains(value.String(), "-"). Hope to find the root cause and give the best solution.

**Environment**:
- App version: v1.5
- Kubernetes version (use `kubectl version`): 1.20
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by saintube** [comment]
> checkMinQuotaSum all children's MinQuota > current MinQuota, current: cluster-root-quota, childMinSum: cpu: 23838, memory: 87751Gi, gpu: 724, newQuotaInfoMin: cpu: 500k, memory: 100000Gi, gpu: 20k

@qinfustu It seems you have modified the quota webhook since the vanilla version does not print the following quantities. Perhaps we should find out the cause first about why the memory.Value() in the example shows an incorrect value, as it is supposed to be calculated by the childMinSum.Memory().Sub(newQuotaInfoMin.Memory()).

**Comment by qinfustu** [comment]
@saintube In order to troubleshoot this problem, new log information has been added. The guess is that there is a problem with the memory.Value() method in scenarios where the numerical value is large and negative. I haven't found the reason after looking at the source code. I need your help.

**Comment by saintube** [comment]
> @saintube In order to troubleshoot this problem, new log information has been added. The guess is that there is a problem with the memory.Value() method in scenarios where the numerical value is large and negative. I haven't found the reason after looking at the source code. I need your help.

@qinfustu How about adding a UT to verify this case?

**Comment by qinfustu** [comment]
> @qinfustu How about adding a UT to verify this case?

@saintube  LessThanOrEqualCompletely's UT did not find the problem.
```go
func TestLessThanOrEqualCompletely(t *testing.T) {
	a := corev1.ResourceList{
		corev1.ResourceCPU:    *resource.NewQuantity(23838, resource.DecimalSI),
		corev1.ResourceMemory: *resource.NewQuantity(87751*1024*1024*1024, resource.BinarySI),
		"nvidia.com/gpu":      *resource.NewQuantity(724, resource.DecimalSI),
	}
	b := corev1.ResourceList{
		corev1.ResourceCPU:    *resource.NewQuantity(500000, resource.DecimalSI),
		corev1.ResourceMemory: *resource.NewQuantity(300000*1024*1024*1024, resource.BinarySI),
		"nvidia.com/gpu":      *resource.NewQuantity(20000, resource.DecimalSI),
	}
	result := LessThanOrEqualCompletely(a, b)
	fmt.Println(result)
	assert.Equal(t, true, result)
}

``` 

But there is a problem with the real scene.

```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  labels:
    quota.scheduling.koordinator.sh/allow-lent-resource: "false"
    quota.scheduling.koordinator.sh/is-parent: "true"
    quota.scheduling.koordinator.sh/parent: koordinator-root-quota
  name: cluster-root-quota-test
  namespace: koordinator-system
spec:
  max:
    cpu: "500000"
    memory: 300000Gi
    nvidia.com/gpu: "20000"
  min:
    cpu: "500000"
    memory: 300000Gi
    nvidia.com/gpu: "20000"
---

apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  labels:
    quota.scheduling.koordinator.sh/allow-lent-resource: "false"
    quota.scheduling.koordinator.sh/is-parent: "false"
    quota.scheduling.koordinator.sh/parent: cluster-root-quota-test
  name: cluster-root-quota-child-test
  namespace: koordinator-system
spec:
  max:
    cpu: "23838"
    memory: 87751Gi
    nvidia.com/gpu: "724"
  min:
    cpu: "23838"
    memory: 87751Gi
    nvidia.com/gpu: "724"
```
Modify the memory in cluster-root-quota-test to 200000Gi to reproduce the problem.
**Error message：**
error: elasticquotas.scheduling.sigs.k8s.io "cluster-root-quota-test" could not be patched: admission webhook "velasticquota.koordinator.sh" denied the request: checkMinQuotaSum all children's MinQuota > current MinQuota, current: cluster-root-quota-test, childMinSum: cpu: 23838, memory: 87751Gi, gpu: 724, newQuotaInfoMin: cpu: 500k, memory: 200000Gi, gpu: 20k

**debug information：**
resource.go:273] delta: cpu: -476162, memory: -112249Gi, gpu: -19276
resource.go:276] k: cpu, value: -476162, valueS: -476162
resource.go:276] k: memory, value: 4579775443, valueS: -112249Gi
