### ISSUE TITLE
[question]priorityClassName和koordinator.sh/priority label的关系是什么，取值有限制么,koordinator.sh/priority必须高于priorityClassName的值么

### ISSUE THREAD

**Issue by 13567436138** [koordinator-sh/koordinator#2255]
**What happened:**
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
    koordinator.sh/priority: "5300"
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: koord-batch
```
[question]priorityClassName和koordinator.sh/priority label的关系是什么，取值有限制么,koordinator.sh/priority必须高于priorityClassName的值么

**What you expected to happen:**

**Environment:**

- Koordinator version: - v0.6.2
- Kubernetes version (use kubectl version): v1.22.5
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**
