### ISSUE TITLE
[proposal] Support RDMA share

### ISSUE THREAD

**Issue by zqzten** [koordinator-sh/koordinator#2337]
**What is your proposal**:
Introduce a new resource `koordinator.sh/rdma.share` similar to the `gpu.share` to support share use of RDMA devices.
Notice that unlike GPU share, RDMA share does not impose any resource isolation so no partial RDMA resource would be introduced.

**Why is this needed**:
Some use cases:
* RDMA devices do not support SRIOV
* Users do not require strict isolation for RDMA networking resoure

**Is there a suggested solution, if so, please add it**:
Maybe we should only allow joint allocation in this case, because shared RDMA itself has no resource limitation for scheduler to consider.

**Comment by zqzten** [comment]
@ZiMengSheng @ferris-cx What's your opinion?

**Comment by ZiMengSheng** [comment]
Currently, Koordlet reports a network card as koordinator.sh/rdma: 100. Can we directly use koordinator.sh/rdma: 1 to indicate a request for shared resources?

**Comment by zqzten** [comment]
> Currently, Koordlet reports a network card as koordinator.sh/rdma: 100. Can we directly use koordinator.sh/rdma: 1 to indicate a request for shared resources?

This cannot handle the case where user wants to apply more than one shared RDMA card.

**Comment by zqzten** [comment]
After some researching, this can be done by the following config:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    scheduling.koordinator.sh/device-allocate-hint: '{"rdma":{"allocateStrategy":"RequestsAsCount"}}'
spec:
  containers:
  - resources:
      limits:
        koordinator.sh/rdma: 2
  ...
```
This requests two shared RDMAs.
