### ISSUE TITLE
[BUG]ElasticQuota did not work in 1.5

### ISSUE THREAD

**Issue by dongliangwu** [koordinator-sh/koordinator#2342]
**What happened**:
QuotaOverUsedRevokeController did not evict pod because runtime in quotaInfo is wrong
**What you expected to happen**:
runtime in quotaInfo Should be correctly modified
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by ZiMengSheng** [comment]
@shaloulcy PTAL

**Comment by ZiMengSheng** [comment]
Please give more details abount quota, pod and cli-args of scheduler.

**Comment by shaloulcy** [comment]
@dongliangwu do you set the args MonitorAllQuotas/EnableRuntimeQuota  to true

**Comment by dongliangwu** [comment]
> [@dongliangwu](https://github.com/dongliangwu) do you set the args MonitorAllQuotas/EnableRuntimeQuota to true

already set MonitorAllQuotas; default value for EnableRuntimeQuota is true ,so i did not set this parameter；

**Comment by dongliangwu** [comment]
> [@dongliangwu](https://github.com/dongliangwu) do you set the args MonitorAllQuotas/EnableRuntimeQuota to true

hello,still on it?

**Comment by saintube** [comment]
PTAL /cc @shaloulcy 
和兄弟 quota runtime 未更新有关吗

**Comment by LennonChin** [comment]
> PTAL /cc [@shaloulcy](https://github.com/shaloulcy) 和兄弟 quota runtime 未更新有关吗

我描述下我和 @cntigers 测下来的一些场景。

场景一：
queue-a 和 queue-b 是兄弟 quota，提交 pod 到 queue-a 里，借用了 queue-b 的资源，同时 queue-a 里还有 pod 在 pending，此时向 queue-b 里提交 pod，queue-a 借用的资源可以被要回，因为此时 queue-a 里 pending 的 pod 会不断尝试调度，触发 queue-a 的 runtime 正确更新，计算得到 used > runtime，queue-a 的资源就被要求返回了。

场景二：
queue-a 和 queue-b 是兄弟 quota，提交 pod 到 queue-a 里，借用了 queue-b 的资源，同时 queue-a 里只有 running 的 pod，没有其他状态的 pod，也没有新提交的 pod，此时向 queue-b 里提交 pod，queue-a 借用的资源无法要回，queue-b 提交的 pod 也会一直 pending，虽然 queue-b 的 runtime 被更新了，但是 queue-a 因为没有发起新的 pod 调度（ 因为没有 pending 的 pod，也没有新提交的 pod），导致 queue-a 的 runtime 一直没更新。如果此时向 queue-a 新提交一个 pod，会触发 queue-a 的 runtime 被更新，此时 queue-a 借用的资源会成功返回。

分析了下源码 pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go 的 refreshRuntimeNoLock 方法里，看逻辑只更新了所有父级 quota 的 runtime，没有更新兄弟 quota 的 runtime，导致被借用的资源无法返还，跟我们测试的场景出现的情况类似。

**Comment by Xdydy** [comment]
I want to test the pod evict on v1.6.0, and I install the koordinator with the config below

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-scheduler-config
  namespace: {{ .Values.installation.namespace }}
data:
  koord-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceLock: leases
      resourceName: koord-scheduler
      resourceNamespace: {{ .Values.installation.namespace }}
    profiles:
      - pluginConfig:
        ...
        - name: ElasticQuota
          args:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: ElasticQuotaArgs
            quotaGroupNamespace: {{ .Values.installation.namespace }}
            enableCheckParentQuota: true # Here I set the True
            enableRuntimeQuota: true
            monitorAllQuotas: true
            revokePodInterval: 5s
            delayEvictTime: 5s
```

And I create 3 quotas below. Here I set the `quota-child1`'s min resources to 0 means that there is no guaranteed for `quota-child1`. When one pod's quota is set to `quota-child1`, it can be killed at any time. 

```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-parent
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/is-parent: "true"
spec:
  max:
    cpu: 500m
    memory: 40Mi
  min:
    cpu: 500m
    memory: 40Mi
---
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-child1
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/is-parent: "false"
    quota.scheduling.koordinator.sh/parent: "quota-parent"
spec:
  max:
    cpu: 500m
    memory: 40Mi
  min:
    cpu: 0
    memory: 0
---
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-child2
  namespace: default
  annotations:
    quota.scheduling.koordinator.sh/evict-pods-exceed-min: "true" 
  labels:
    quota.scheduling.koordinator.sh/is-parent: "false"
    quota.scheduling.koordinator.sh/parent: "quota-parent"
spec:
  max:
    cpu: 500m
    memory: 40Mi
  min:
    cpu: 500m
    memory: 40Mi
```

And I first create the `pod-example`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/name: "quota-child1"
spec:
  schedulerName: koord-scheduler
  containers:
  - command:
    - sleep
    - 5m
    image: busybox
    imagePullPolicy: IfNotPresent
    name: curlimage
    resources:
      limits:
        cpu: 40m
        memory: 30Mi
      requests:
        cpu: 40m
        memory: 30Mi
  restartPolicy: Never
```

After the `pod-example`'s status is `running`, I create the `pod2-example`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod2-example
  namespace: default
  labels:
    quota.scheduling.koordinator.sh/name: "quota-child2"
spec:
  schedulerName: koord-scheduler
  containers:
  - command:
    - sleep
    - 5m
    image: busybox
    imagePullPolicy: IfNotPresent
    name: curlimage
    resources:
      limits:
        cpu: 40m
        memory: 30Mi
      requests:
        cpu: 40m
        memory: 30Mi
  restartPolicy: Never
```

Since the memory sum of the two pods(60Mi) is greater than the max of `parent-quota`(50Mi), `pod2-example` is at status `pending` because of the code below. 

https://github.com/koordinator-sh/koordinator/blob/0cae469414a5a0b40eb9b952a690b269b21e2d0c/pkg/scheduler/plugins/elasticquota/plugin.go#L270

So I set the configmap and reinstall the koordinator

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: koord-scheduler-config
  namespace: {{ .Values.installation.namespace }}
data:
  koord-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceLock: leases
      resourceName: koord-scheduler
      resourceNamespace: {{ .Values.installation.namespace }}
    profiles:
      - pluginConfig:
        ...
        - name: ElasticQuota
          args:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: ElasticQuotaArgs
            quotaGroupNamespace: {{ .Values.installation.namespace }}
            enableCheckParentQuota: false # Here I set the false
            enableRuntimeQuota: true
            monitorAllQuotas: true
            revokePodInterval: 5s
            delayEvictTime: 5s
```

and repeat the steps above, it will lead to the scene that `pod-example` and the `pod2-example` are running, without evicting any of the pods.

And I see the code below and search the logs it reports that the `parent-quota`'s  used > runtime. 

https://github.com/koordinator-sh/koordinator/blob/0cae469414a5a0b40eb9b952a690b269b21e2d0c/pkg/scheduler/plugins/elasticquota/quota_overuse_revoke.go#L61

However, it did not evict any pods because the pod is not reference for the `parent-quota` 

https://github.com/koordinator-sh/koordinator/blob/0cae469414a5a0b40eb9b952a690b269b21e2d0c/pkg/scheduler/plugins/elasticquota/core/group_quota_manager.go#L742-L765

Is it a bug? Or is there other code I ingore?
