### ISSUE TITLE
[BUG] The Pod cannot be scheduled because the runtimeQuota is less than the minQuota

### ISSUE THREAD

**Issue by qinfustu** [koordinator-sh/koordinator#2393]
**What happened**:
The Pod fails to schedule because ​the calculated runtimeQuota is less than the minQuota when the requested resources exceed the defined minimum threshold. Quota information as follows:

```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  annotations:
    quota.scheduling.koordinator.sh/child-request: '{"cpu":"200500m","memory":"819712Mi","nvidia.com/gpu":"8"}'
    quota.scheduling.koordinator.sh/request: '{"cpu":"200500m","memory":"819712Mi","nvidia.com/gpu":"8"}'
    quota.scheduling.koordinator.sh/runtime: '{"cpu":"197819m","memory":"749671274133","nvidia.com/gpu":"7"}'
    quota.scheduling.koordinator.sh/shared-weight: '{"cpu":"200","memory":"20000Gi","nvidia.com/gpu":"8"}'
  labels:
    quota.scheduling.koordinator.sh/allow-lent-resource: "true"
    quota.scheduling.koordinator.sh/is-parent: "true"
    quota.scheduling.koordinator.sh/parent: cluster-root-quota.gpu
  name: quota-pub.gpu
  namespace: koordinator-system
spec:
  max:
    cpu: "200"
    memory: 1000Gi
    nvidia.com/gpu: "8"
  min:
    cpu: "200"
    memory: 1000Gi
    nvidia.com/gpu: "8"
status:
  used:
    cpu: "100"
    memory: 400Gi
    nvidia.com/gpu: "4"

---

apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  annotations:
    quota.scheduling.koordinator.sh/child-request: '{"cpu":"200","memory":"819712Mi","nvidia.com/gpu":"8"}'
    quota.scheduling.koordinator.sh/request: '{"cpu":"218","memory":"1500Gi","nvidia.com/gpu":"8"}'
    quota.scheduling.koordinator.sh/runtime: '{"cpu":"197819m","memory":"749671274133","nvidia.com/gpu":"7"}'
    quota.scheduling.koordinator.sh/shared-weight: '{"cpu":"200","memory":"20000Gi","nvidia.com/gpu":"2000"}'
  labels:
    quota.scheduling.koordinator.sh/allow-lent-resource: "false"
    quota.scheduling.koordinator.sh/is-parent: "true"
    quota.scheduling.koordinator.sh/parent: koordinator-root-quota
  name: cluster-root-quota.gpu
  namespace: koordinator-system
spec:
  max:
    cpu: "218"
    memory: 1500Gi
    nvidia.com/gpu: "8"
  min:
    cpu: "218"
    memory: 1500Gi
    nvidia.com/gpu: "8"
status:
  used:
    cpu: "100"
    memory: 400Gi
    nvidia.com/gpu: "4"
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: 1.6.0
- Kubernetes version (use `kubectl version`): 1.28
- Install details (e.g. helm install args): helm
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:
