### ISSUE TITLE
[BUG]elasticquota 中的资源借用后未归还

### ISSUE THREAD

**Issue by cntigers** [koordinator-sh/koordinator#2432]
elasticquota 中的资源借用后未归还；
疑问：
1. 借用未归还的原因
2. 归还也是通过驱逐实现的吗？
3. 重新计算runtime资源量的触发动作有哪些
复现逻辑如下：
启动pod-example2，后再启动pod-example1 ；pod-example2可以正常运行，但是pod-example1一直未pending状态，报错如下：

![Image](https://github.com/user-attachments/assets/df37b892-4b39-4262-8ef6-3c34028c4965)

具体配置如下：

其中父elasticquota配置如下：
```
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-parent-example
  namespace: ns-elasticquota
  labels:
    quota.scheduling.koordinator.sh/parent: "koordinator-root-quota"
    quota.scheduling.koordinator.sh/is-parent: "true"
    quota.scheduling.koordinator.sh/allow-lent-resource: "true"
spec:
  max:
    cpu: 12
    kubernetes.io/batch-cpu: 5k
    kubernetes.io/batch-memory: 5Gi
    memory: 6Gi
  min:
    cpu: 12
    kubernetes.io/batch-cpu: 5k
    memory: 6Gi
    kubernetes.io/batch-memory: 5Gi
```

child1 elasticquota配置如下

```
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-example
  namespace: ns-elasticquota
  annotations:
  labels:
    quota.scheduling.koordinator.sh/is-parent: "false"
    quota.scheduling.koordinator.sh/parent: "quota-parent-example"
    quota.scheduling.koordinator.sh/allow-lent-resource: "true"
spec:
  max:
    cpu: 16
    kubernetes.io/batch-cpu: 5k
    kubernetes.io/batch-memory: 5Gi
    memory: 6Gi
  min:
    cpu: 8
    kubernetes.io/batch-cpu: 4k
    memory: 4Gi
    kubernetes.io/batch-memory: 4Gi
```

child2的elasticquota配置如下：

```
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota-example2
  namespace: ns-elasticquota
  labels:
    quota.scheduling.koordinator.sh/is-parent: "false"
    quota.scheduling.koordinator.sh/parent: "quota-parent-example"
    quota.scheduling.koordinator.sh/allow-lent-resource: "true"
spec:
  max:
    cpu: 8
    memory: 6Gi
    kubernetes.io/batch-cpu: 1k
    kubernetes.io/batch-memory: 100Mi
  min:
    cpu:  4
    memory: 2000Mi
    kubernetes.io/batch-cpu: 1k
    kubernetes.io/batch-memory: 100Mi
```

pod2配置如下：
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-example2
  namespace: ns-elasticquota2
  labels:
    test-qos: "ls-prod"
    quota.scheduling.koordinator.sh/name: "quota-example2"
spec:
  schedulerName: koord-scheduler
 # nodeName: node2
  containers:
  - name: nginx-container
    image: harbor.dap.local/library/nginx:1.22  # 使用包含 stress 工具的镜像
    resources:
      limits:
        cpu: 8
        memory: 400Mi
      requests:
        cpu: 8
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  restartPolicy: Always
```

pod1配置如下：
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-example1
  namespace: ns-elasticquota2
  labels:
    test-qos: "ls-prod"
    quota.scheduling.koordinator.sh/name: "quota-example"
    #koordinator.sh/qosClass: "LS"
spec:
  schedulerName: koord-scheduler
  #priorityClassName: koord-prod
  containers:
  - name: nginx
    image: harbor.dap.local/library/nginx:1.22  # 使用包含 stress 工具的镜像
    resources:
      limits:
        cpu: 7
        memory: 200Mi
      requests:
        cpu: 7
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  restartPolicy: Always
```

**Environment**:
- App version: 1.6.0
- Kubernetes version (use `kubectl version`): 1.22
- Others:
