### ISSUE TITLE
[proposal]​​ Improve Validation for Reservation CRD Template Fields​

### ISSUE THREAD

**Issue by qinfustu** [koordinator-sh/koordinator#2502]
**What is your proposal**:

Current Problem​​:
The template field in the Reservation CRD currently ​​lacks validation​​, allowing users to fill in all fields inherited from the standard Pod specification. This design introduces several issues:

1. Redundant Configuration​​: Most Pod fields are ​​irrelevant for reservations​​ (e.g., container images, lifecycle hooks), exposing unnecessary configuration complexity to users.
2. High Cognitive Barrier​​: Users struggle to determine ​​which fields are functional​​ (e.g., resource requests, node affinity) vs. ​​ignored fields​​, leading to misconfigurations and debugging overhead.
3. Validation Complexity​​: Supporting the entire Pod spec necessitates replicating complex validation logic, increasing maintenance costs and risk of inconsistencies.

**Why is this needed**:
e.g.
The reservation has a configured label: **quota.scheduling.koordinator.sh/name: quota**, causing it to remain in a Pending state. Events indicate this is due to insufficient quota. Testing confirms that quota validation is enforced during reservation scheduling, but this behavior is unexpected. Otherwise, when the owner Pod schedules, the quota will be recalculated and consumed again.
reservation conditions:
  

>     message: '0/8 nodes are available: Insufficient quotas [[cpu memory]], quotaName:
>       quota, runtime: cpu:0,memory:0,nvidia.com/gpu:0, used: <empty>, pod''s
>       request: cpu:6,memory:8Gi, exceedDimensions: [cpu memory]. preemption: pod "eee75895-031e-4d14-a6d8-e50edc5d5bae"
>       not found.'
>     reason: Unschedulable
>     status: "False"
>     type: Scheduled
quota info:
```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  annotations:
    quota.scheduling.koordinator.sh/runtime: '{"cpu":"0","memory":"0","nvidia.com/gpu":"0"}'
    quota.scheduling.koordinator.sh/request: '{}'
  name: quota
  namespace: koordinator-system
spec:
  max:
    cpu: "320"
    memory: 1100Gi
    nvidia.com/gpu: "0"
  min:
    cpu: "320"
    memory: 1100Gi
    nvidia.com/gpu: "0"
status:
  used:
    cpu: "0"
    memory: "0"
```

**Is there a suggested solution, if so, please add it**:

1. Add parameter validation for the template to clarify which fields are required and which are unsupported.
2. Alternatively, replace the Pod template with a ​​custom parameter set​​ tailored for reservation use cases.
