### ISSUE TITLE
[BUG] Reservation status got duplicated owners when scheduler is not permitted to patch pod.

### ISSUE THREAD

**Issue by saintube** [koordinator-sh/koordinator#429]
**What happened**:

In koordinator v0.5, the default koord-scheduler service account has no permission to patch pods, while the reservation plugin patches pods with annotations of reservation allocated info. So with the default RBAC, the reservation plugin cannot patch the pod which allocates a reservation, and then the `CurrentOwners` status will display duplicated info of the pod.

```yaml
apiVersion: scheduling.koordinator.sh/v1alpha1
kind: Reservation
metadata:
  name: reservation-sample
  ...
spec:
  ...
status:
  allocatable:
    cpu: 500m
    memory: 800Mi
  allocated:
    cpu: 200m
    memory: 400Mi
  conditions:
  - lastProbeTime: "2022-08-02T02:23:50Z"
    lastTransitionTime: "2022-08-02T02:23:50Z"
    reason: Scheduled
    status: "True"
    type: Scheduled
  - lastProbeTime: "2022-08-02T02:23:50Z"
    lastTransitionTime: "2022-08-02T02:23:50Z"
    reason: Available
    status: "True"
    type: Ready
  currentOwners:
  - name: reserve-demo-0
    namespace: default
    uid: xxxx
  - name: reserve-demo-0
    namespace: default
    uid: xxxx
  - name: reserve-demo-0
    namespace: default
    uid: xxxx
```

**What you expected to happen**:

The plugin should not make duplicated owner statuses in a reservation.

**How to reproduce it (as minimally and precisely as possible)**:

1. Remove the pod patch permission in koord-scheduler RBAC.
2. Create a reservation to reserve resources.
3. Create a pod to allocate reserved resources.
4. Check the owner status of reservation.

**Anything else we need to know?**:

**Environment**:
- App version: v0.5
- Kubernetes version (use `kubectl version`): 1.22
- Install details (e.g. helm install args):
- Others:
