### ISSUE TITLE
[BUG]koord-runtime-proxy failed to proxy exec request without -it option 

### ISSUE THREAD

**Issue by cheimu** [koordinator-sh/koordinator#437]
**What happened**:
Any scenario involving with exec request, including `ExecSync` for docker, `PostStartHook` for pod Lifecycle, and readiness probe etc., the exec will be failed as shown below.
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/13050415/182624107-78d2aca1-506a-45e1-a902-449f3b3d5352.png">

**What you expected to happen**:
They should be executed successfully.

**How to reproduce it (as minimally and precisely as possible)**:
It is very easy to reproduce. As long as echo something when exec. For example, the following pod manifest has a `postStart` hook and `echo 1` . It will fail to start pods and the error is the screenshot from the above.
```
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
  - env:
    - name: TEST
      value: value0
    image: nginx:1.20.1-alpine
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - echo 1 && sleep 2s
    name: main
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 80
      timeoutSeconds: 1
```

**Anything else we need to know?**:
We found a very interesting fact: 
When try to manually trigger it using docker cli
```
docker --host=unix:///var/run/runtimeproxy/runtimeproxy.sock exec -it 246ab5790f80 /bin/sh -c "echo 1 && sleep 2s"
```
Everything is doing well. However, when remove `-it` flag 
```
docker --host=unix:///var/run/runtimeproxy/runtimeproxy.sock exec 246ab5790f80 /bin/sh -c "echo 1 && sleep 2s"
```
The error reproduced.
It turns out that, kubelet will set `in` to `nil` and `tty` to `false` when doing `exec`. 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/13050415/182622677-c93aacbc-5a68-4967-86f3-af01242f3cf3.png">

And koord-runtime-proxy only proxies `exec` request without intercepting. We highly doubt the problem is the reverse proxy.
<img width="861" alt="image" src="https://user-images.githubusercontent.com/13050415/182626994-f086c640-2bfa-4610-98ca-4e8bf323b7a3.png">

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18
