### ISSUE TITLE
[BUG] not syncing NodeSLO from configMap slo-controller-config

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#84]
**What happened**:
1. Not syncing to NodeSLO after `memoryEvictThresholdPercent` of `resource-threshold-config` in configMap `slo-controller-config`  

**What you expected to happen**:
Expect syncing to NodeSLO with `memoryEvictThresholdPercent` of `resource-threshold-config`

**How to reproduce it (as minimally and precisely as possible)**:
1. update configMap `slo-controller-config`
```yaml
apiVersion: v1
data:
  colocation-config: |
    {
      "enable": true
    }
  resource-threshold-config: |
    {
      "clusterStrategy": {
        "enable": true,
        "memoryEvictThresholdPercent": 70
      }
    }
kind: ConfigMap
metadata:
  name: slo-controller-config
  namespace: koordinator-system
```
2.  check NodeSLO
```shell
$ kubectl get nodeslo -o yaml | grep memoryEvictThresholdPercent # get nothing
```

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:
